### ISSUE TITLE
v1.14 release status

### ISSUE THREAD

**Issue by twmb** [twmb/franz-go#487]
kmsg proto bumps:
- [x] KIP-405 proto #485
- [x] KIP-903 proto #484

kgo:
- [x] bump pinned kmsg
- [x] DialTLS #483
- [x] NodeName, Opts #495 
- [x] Add kraft detection to kversion #497
- [x] KeepRetryableFetchErrors #439
- [x] Optional SASL Validate interface #472
- [x] AddConsumePartitions #475
- [x] Tolerate buggy group member metadata #493 
- [x] Make dial timeouts retryable
- [x] Add info to opportunistic load during source backoff -- say why
- [x] Add debug logging when stripping partitions when fetching
- [x] Add getters to Offset (return EpochOffset)
- [x] Allow mixing OnBrokerRead && OnBrokerWrite
- [x] Avoid returning partitions after pause #489

Deferred:
- [x] ~Per-partition consumer helper?~
