### ISSUE TITLE
v1.17 release status

### ISSUE THREAD

**Issue by twmb** [twmb/franz-go#698]
- [x] Support Kafka 3.7 (as well as Errors.java)
- [x] Ready to merge: #672 
- [x] Ready to merge: #681 
- [x] Ready to merge: #697
- [x] Fix #686 
- [x] ~Investigate whether the new preview consumer group behavior is worth supporting yet~ NO, it is not advertised in ApiVersions
- [x] #692
- [x] Bump all deps
- [x] Add broker info to Fetch
- [x] Update readme for KIP

~- [ ] Add batch timing to ProduceBatchMetrics?~ need more detail
- [ ] Review #506 -- CUT, to follow (not part of kgo)
- [ ] Review and merge: #691 -- CUT, to follow (not part of kgo)
